# version: '3.9'

# services:

#   timescaledb:
#     image: timescale/timescaledb:latest-pg16
#     container_name: timescaledb
#     restart: always
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     ports:
#       - "${DB_PORT}:5432"
#     volumes:
#       - timescale-data:/var/lib/postgresql/data
#     networks:
#       - thermo_sense_network
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   auth-service:
#     build:
#       context: ./services/auth-service/
#       dockerfile: Dockerfile
#     container_name: auth_service
#     image: auth_service:latest
#     env_file:
#       - ./.env
#     ports:
#       - "4100:4100"
#     depends_on:
#       - customer-service
#     networks:
#       - thermo_sense_network
#     healthcheck:
#       test: ["CMD-SHELL", "curl -f http://localhost:4100/sensor/latest || exit 1"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#     restart: always



# networks:
#   thermo_sense_network:
#     driver: bridge

# volumes:
#   timescale-data: